### ISSUE TITLE
App fora do ar

### ISSUE THREAD

**Issue by israelhudson** [robsonsilv4/queroworkar#1]
Não aparece a lista de vagas na home do app

**Comment by robsonsilv4** [comment]
Obrigado por avisar @israelhudson, o site realmente está fora do ar.
Irei adotar alguma técnica de espelhamento para evitar que isso aconteça novamente.

**Comment by israelhudson** [comment]
Legal Robson pode ser adotado uma técnica de cache da lista. Posso te ajudar com isso quando o site voltar...

**Comment by robsonsilv4** [comment]
Desculpa a demora @israelhudson, estava contribuindo em outros projetos.

E com certeza sua ajuda será bem bem vinda :)

Na época eu havia adicionado o hydrated_bloc como dependência e ele acaba funcionando como cache, mantendo o estado inicial do bloc desde a última requisição. Mas ele só lida com String ou Map de String e como estava armazenando objetivos, não soube resolver.

Mas aprendi bastante coisa desde de quando criei a aplicação e vou tirar um tempo para melhorar a arquitetura e funcionalidades, até para facilitar as contribuições. Espero que após isso, possa contar com você e com todos que gostam do QueroWorkar ;)

**Comment by robsonsilv4** [comment]
Ah, o site voltei :)

Vou abrir depois uma issue sobre a melhor alternativa de cache, para evitar que a aplicação fique fora do ar também.

**Comment by israelhudson** [comment]
Entendido Robson. Estava pensando em mandar um PR desse projeto com uma arquitetura mais simples para outras pessoas de skill menor também contribuam.
